# Generated by Django 5.0 on 2023-12-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='templates.emailtemplate', verbose_name='email template'),
        ),
    ]
